(* This file has been autogenerated by mir-crunch *)
module Internal = struct
let file_chunks = function
 | _ -> None

let file_list = [ ]
let size = function
 |_ -> None

end

let name="static"

open Lwt

exception Error of string

let iter_s fn = Lwt_list.iter_s fn Internal.file_list

let size name = return (Internal.size name)

let read name =
  match Internal.file_chunks name with
  |None -> return None
  |Some c ->
     let chunks = ref c in
     return (Some (Lwt_stream.from (fun () ->
       match !chunks with
       |hd :: tl -> 
         chunks := tl;
         let pg = OS.Io_page.get () in
         let len = String.length hd in
         Cstruct.set_buffer hd 0 pg 0 len;
         return (Some (Cstruct.sub pg 0 len))
       |[] -> return None
     )))

let create vbd : OS.Devices.kv_ro Lwt.t =  
  return (object
    method iter_s fn = iter_s fn
    method read name = read name
    method size name = size name
  end)

let _ =
  let plug = Lwt_mvar.create_empty () in
  let unplug = Lwt_mvar.create_empty () in
  let provider = object(self)
    method id = name
    method plug = plug
    method unplug = unplug
    method create ~deps ~cfg id =
      Lwt.bind (create id) (fun kv ->
        let entry = OS.Devices.({
           provider=self;
           id=self#id;
           depends=[];
           node=KV_RO kv }) in
        return entry
      )
  end in
  OS.Devices.new_provider provider;
  OS.Main.at_enter (fun () -> Lwt_mvar.put plug {OS.Devices.p_id=name; p_dep_ids=[]; p_cfg=[]})

